[project]
name = "satsp"
version = "0.0.1"
dependencies = [
    "tsplib95",
    "requests",
    "numpy",
    "tqdm",
    "matplotlib"
]
description = "Simulated Anealing for Traveling Salesman Problem" 

[tool.setuptools]
packages = ["satsp"]